services:
  backend:
    build: ./backend
    container_name: control-backend
    restart: always
    ports:
      - "3000:3000" # Opcional, solo para debug
    volumes:
      # Esto guarda la BD en tu carpeta local para que no se borre al reiniciar docker
      - ./backend/database.sqlite:/app/database.sqlite

  frontend:
    build: ./frontend
    container_name: control-frontend
    restart: always
    ports:
      - "80:80" # El puerto web est√°ndar
    depends_on:
      - backend