services:
  backend:
    build: ./backend
    container_name: control-backend
    restart: always
    ports:
      - "3000:3000"
<<<<<<< HEAD
    environment:
      - TZ=America/Lima # HORA PERÚ (Importante para la asistencia)
    env_file:
      - ./backend/.env # Inyecta las variables secretas
=======
    env_file:
      - ./backend/.env
>>>>>>> 5af1175774124d24090195cfb5b10c8560211e6c
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite

  frontend:
    build: ./frontend
    container_name: control-frontend
    restart: always
    ports:
      - "80:80" # El puerto web estándar
    depends_on:
      - backend
