services:
  backend:
    build: ./backend
    container_name: control-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite

  frontend:
    build: ./frontend
    container_name: control-frontend
    restart: always
    ports:
      - "80:80" # El puerto web estÃ¡ndar
    depends_on:
      - backend
